version: "3"

services:

  runtime-setup:
    image: swift-service-discovery:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-service-discovery:22.04-main
    environment: []
      #- SANITIZER_ARG=--sanitize=thread
    command: /bin/bash -xcl "swift test $${SANITIZER_ARG-}" # Disable -warnings-as-errors due to Sendable warnings

  shell:
    image: swift-service-discovery:22.04-main
