version: "3"

services:

  runtime-setup:
    image: swift-service-discovery:20.04-5.7
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.7-focal"

  test:
    image: swift-service-discovery:20.04-5.7
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-service-discovery:20.04-5.7
